title: Olga Horn
description: Personal website
baseurl: "/olga-horn"
url: "https://a-ast.github.io"

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: "de"
    values:
      lang: de
      layout: default
  - scope:
      path: "ru"
    values:
      lang: ru
      layout: default
  - scope:
      path: "de/news"
    values:
      sidebar_folder: "/de/news/"
  - scope:
      path: "ru/news"
    values:
      sidebar_folder: "/ru/news/"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
